//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketPlace.Client.MarketPlaceSelfHostService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MarketPlaceSelfHostService.IMarketPlaceService")]
    public interface IMarketPlaceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketPlaceService/GetProduct", ReplyAction="http://tempuri.org/IMarketPlaceService/GetProductResponse")]
        MarketPlace.Model.Entities.Product GetProduct(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketPlaceService/GetProduct", ReplyAction="http://tempuri.org/IMarketPlaceService/GetProductResponse")]
        System.Threading.Tasks.Task<MarketPlace.Model.Entities.Product> GetProductAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketPlaceService/CreatePurchase", ReplyAction="http://tempuri.org/IMarketPlaceService/CreatePurchaseResponse")]
        void CreatePurchase(MarketPlace.Model.Entities.Purchase purchase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketPlaceService/CreatePurchase", ReplyAction="http://tempuri.org/IMarketPlaceService/CreatePurchaseResponse")]
        System.Threading.Tasks.Task CreatePurchaseAsync(MarketPlace.Model.Entities.Purchase purchase);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMarketPlaceServiceChannel : MarketPlace.Client.MarketPlaceSelfHostService.IMarketPlaceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MarketPlaceServiceClient : System.ServiceModel.ClientBase<MarketPlace.Client.MarketPlaceSelfHostService.IMarketPlaceService>, MarketPlace.Client.MarketPlaceSelfHostService.IMarketPlaceService {
        
        public MarketPlaceServiceClient() {
        }
        
        public MarketPlaceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MarketPlaceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MarketPlaceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MarketPlaceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MarketPlace.Model.Entities.Product GetProduct(string id) {
            return base.Channel.GetProduct(id);
        }
        
        public System.Threading.Tasks.Task<MarketPlace.Model.Entities.Product> GetProductAsync(string id) {
            return base.Channel.GetProductAsync(id);
        }
        
        public void CreatePurchase(MarketPlace.Model.Entities.Purchase purchase) {
            base.Channel.CreatePurchase(purchase);
        }
        
        public System.Threading.Tasks.Task CreatePurchaseAsync(MarketPlace.Model.Entities.Purchase purchase) {
            return base.Channel.CreatePurchaseAsync(purchase);
        }
    }
}
