//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketPlace.Client.MarketPlaceSelfHostService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MarketPlaceSelfHostService.IMarketPlaceService")]
    public interface IMarketPlaceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketPlaceService/GetProducts", ReplyAction="http://tempuri.org/IMarketPlaceService/GetProductsResponse")]
        MarketPlace.Model.Entities.Product[] GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketPlaceService/GetProducts", ReplyAction="http://tempuri.org/IMarketPlaceService/GetProductsResponse")]
        System.Threading.Tasks.Task<MarketPlace.Model.Entities.Product[]> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketPlaceService/GetProduct", ReplyAction="http://tempuri.org/IMarketPlaceService/GetProductResponse")]
        MarketPlace.Model.Entities.Product GetProduct(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketPlaceService/GetProduct", ReplyAction="http://tempuri.org/IMarketPlaceService/GetProductResponse")]
        System.Threading.Tasks.Task<MarketPlace.Model.Entities.Product> GetProductAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketPlaceService/CreateProduct", ReplyAction="http://tempuri.org/IMarketPlaceService/CreateProductResponse")]
        void CreateProduct(string id, string description, decimal price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketPlaceService/CreateProduct", ReplyAction="http://tempuri.org/IMarketPlaceService/CreateProductResponse")]
        System.Threading.Tasks.Task CreateProductAsync(string id, string description, decimal price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketPlaceService/CreatePurchase", ReplyAction="http://tempuri.org/IMarketPlaceService/CreatePurchaseResponse")]
        void CreatePurchase(System.DateTime date, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketPlaceService/CreatePurchase", ReplyAction="http://tempuri.org/IMarketPlaceService/CreatePurchaseResponse")]
        System.Threading.Tasks.Task CreatePurchaseAsync(System.DateTime date, string content);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMarketPlaceServiceChannel : MarketPlace.Client.MarketPlaceSelfHostService.IMarketPlaceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MarketPlaceServiceClient : System.ServiceModel.ClientBase<MarketPlace.Client.MarketPlaceSelfHostService.IMarketPlaceService>, MarketPlace.Client.MarketPlaceSelfHostService.IMarketPlaceService {
        
        public MarketPlaceServiceClient() {
        }
        
        public MarketPlaceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MarketPlaceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MarketPlaceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MarketPlaceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MarketPlace.Model.Entities.Product[] GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<MarketPlace.Model.Entities.Product[]> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public MarketPlace.Model.Entities.Product GetProduct(string id) {
            return base.Channel.GetProduct(id);
        }
        
        public System.Threading.Tasks.Task<MarketPlace.Model.Entities.Product> GetProductAsync(string id) {
            return base.Channel.GetProductAsync(id);
        }
        
        public void CreateProduct(string id, string description, decimal price) {
            base.Channel.CreateProduct(id, description, price);
        }
        
        public System.Threading.Tasks.Task CreateProductAsync(string id, string description, decimal price) {
            return base.Channel.CreateProductAsync(id, description, price);
        }
        
        public void CreatePurchase(System.DateTime date, string content) {
            base.Channel.CreatePurchase(date, content);
        }
        
        public System.Threading.Tasks.Task CreatePurchaseAsync(System.DateTime date, string content) {
            return base.Channel.CreatePurchaseAsync(date, content);
        }
    }
}
